# Main Hydra configuration file
defaults:
  - model: tfdf
  - data: titanic
  - experiment: baseline
  - _self_

project:
  name: titanic-enterprise
  version: 1.0.0
  random_seed: 1234
  description: "Enterprise ML infrastructure for Titanic survival prediction"

paths:
  data_dir: data
  model_dir: models
  output_dir: outputs
  log_dir: logs
  config_dir: configs

mlflow:
  tracking_uri: file:./mlruns
  experiment_name: titanic-tfdf
  artifact_location: ./mlruns
  registry_uri: file:./mlruns

dvc:
  remote_name: local
  remote_url: ./dvc-storage

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  structured: true

# Environment-specific overrides
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}