# TensorFlow Decision Forests model configuration
_target_: titanic_enterprise.models.tfdf_model.TFDFModel

name: "gradient_boosted_trees"
task: "CLASSIFICATION"

# Model hyperparameters
hyperparameters:
  num_trees: 300
  max_depth: 6
  min_examples: 5
  subsample: 0.9
  sampling_method: "RANDOM"
  
  # Regularization
  l1_regularization: 0.0
  l2_regularization: 0.1
  
  # Learning rate
  shrinkage: 0.1
  
  # Feature selection
  num_candidate_attributes_ratio: 1.0
  
# Training configuration
training:
  verbose: 1
  compute_oob_performances: true
  compute_oob_variable_importances: true
  
# Evaluation metrics
metrics:
  - accuracy
  - precision
  - recall
  - f1_score
  - auc_roc

# Feature importance
feature_importance:
  compute: true
  method: "MEAN_DECREASE_IN_ACCURACY"